/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcon.si.incremental.app;

public class Desktop {
    public String getHello() {
        return "Hello World!";
    }
}
