/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcon.si.incremental.app;

public class App {
    public String run() {
        return new Library().getHello();
    }
}
